[Draft] Add Tizen implementation for Calendar
xamarin/Essentials pull request #1399
Opened 2020-09-29 00:10 UTC by sung-su

### Description of Change ###

Add Tizen implementation for Calendar

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of `main` at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

2020-09-29 00:21 UTC, sung-su commented
@mattleibow Sorry for late. but still needs fix.

2020-09-29 01:50 UTC, mattleibow commented
Sweet! No rush.

2020-10-09 06:51 UTC, Mrnikbobjeff requested changes
Only some minor nitpicks

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +        static IEnumerable<Calendar> ToCalendars(TCalendar.CalendarList calendarList)
This is only called after a tolist call, it would be possible to elide the statemachine if we make this method not yield.

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +                Id = calendarRecord.Get<int>(TCalendarViews.Book.Id).ToString(),
ToString uses the Threads current culture. Specify InvariantCulture to not run into problems with numbergroupseperators, i.e. 1234 => 1.234

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +        static IEnumerable<CalendarEvent> ToEvents(TCalendar.CalendarList eventList)
Same here, why make it a statemachine if we only call tolist afterwards

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +                Id = eventRecord.Get<int>(TCalendarViews.Event.Id).ToString(),
Use InvariantCulture for ToString Calls

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +                CalendarId = eventRecord.Get<int>(TCalendarViews.Event.BookId).ToString(),
Same

2020-10-09 06:51 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +        static IEnumerable<CalendarEventAttendee> ToAttendees(TCalendar.CalendarList attendeeList)
Same here with statemachine

2020-10-09 07:48 UTC, Mrnikbobjeff requested changes
These checks are already done in shared code

2020-10-09 07:48 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +            if (!string.IsNullOrEmpty(calendarId) && !int.TryParse(calendarId, out _))
IsNullOrEmpty is redundant and should be removed. Check already occurs in shared code

2020-10-09 07:48 UTC, Mrnikbobjeff commented on Xamarin.Essentials/Calendars/Calendars.tizen.cs
> +            if (!string.IsNullOrEmpty(eventId) && !int.TryParse(eventId, out _))
Check is redundant, we check in shared code

2020-10-12 08:09 UTC, sung-su commented
Applied comments.

2022-04-05 13:29 UTC, jfversluis commented
Unfortunately this won't be happening for Xamarin.Essentials anymore. Let's see if we can make it happen for .NET MAUI!

2022-04-05 13:29 UTC, closed without merging