[Enhancement] Feature quick preview file
xamarin/Essentials pull request #1713
Opened 2021-03-03 21:41 UTC by andrk0p

### Description of Change ###

Added the ability to quickly view the file inside the iOS app.

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
`static Task PlatformOpenAsync(OpenFileRequest request, bool openInApp)`

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of `main` at time of PR
- [ ] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

2021-03-03 23:53 UTC, jamesmontemagno commented on Xamarin.Essentials/Launcher/Launcher.netstandard.watchos.cs
> +        static Task PlatformOpenAsync(OpenFileRequest request, bool openInApp) =>
No need for another parameter, it should just be in the OpenFileRequest

2021-03-03 23:55 UTC, jamesmontemagno requested changes
I would only add it to the OpenFileRequest. This simplifies the API  so we don't need a new one and can document that it is only an iOS feature.

2021-03-03 23:57 UTC, jamesmontemagno commented on Xamarin.Essentials/Launcher/Launcher.android.cs
> +        static Task PlatformOpenAsync(OpenFileRequest request, bool openInApp) =>
I think we would just add this to "OpenFileReqauest", no need to chagne teh singautre at all

2021-03-04 18:39 UTC, dimonovdd reviewed
LGTM.
But I wrote a few comments. Most importantly we need to change the way we get `UIViewController`

2021-03-04 18:39 UTC, dimonovdd commented on Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs
> +        static Task PlatformOpenAsync(OpenFileRequest request, bool openInApp)
There is no need to create this method. See @jamesmontemagno  comment.

2021-03-04 18:39 UTC, dimonovdd commented on Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs
> +                UIApplication.SharedApplication?.KeyWindow?.RootViewController?.
use [Platform.GetCurrentUIViewController()](https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs#L79)

2021-03-04 18:39 UTC, dimonovdd commented on Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs
> +            ItemTitle = fileName;
`fileName` will be used as a window titlel.  Maybe, we should be able to change it.
A file name doesn't always look good

2021-03-05 19:14 UTC, andrk0p commented
@jamesmontemagno @dimonovdd Thank you for your feedback. I made the changes

2021-03-26 07:45 UTC, IngweLand commented
I do not think that QuickLook should be added to the Essentials. It's a dedicated single-platform feature only, while Essentials is supposed to have cross-platform implementations. 
If you still decide to add it, I think you should also add following things:

- Checking if file is supported in QL (https://developer.apple.com/documentation/quicklook/qlpreviewcontroller/1617016-canpreviewitem)
- Disposing of QLPreviewController and its data source

2022-01-19 20:10 UTC, jfversluis commented
Hey everyone! Thanks for all the effort and input here! At this point in time we're aiming to not add any new functionality anymore as we're transitioning into .NET MAUI. Also, there seems to be some discussion about if this should be in Essentials because it's very specific to one platform.

If this is still of interest to you, please open a discussion on the .NET MAUI repo and if people seem to be in favor we might be able to port this code there. I'm closing if for here for now. Thank you Andrey for your time here!

2022-01-19 20:10 UTC, closed without merging