Added support for reduced accuracy detection on iOS 14
xamarin/Essentials pull request #1739
Opened 2021-03-24 14:19 UTC by leonluc-dev

### Description of Change ###

iOS 14 added the ability for users to grant location permission with reduced accuracy.
In such cases the requested accuracy is ignored and the coarse location is returned.

This PR adds:

* A Location property indicating if the retrieved location has reduced accuracy (if true, the accuracy was intentionally reduced by the user through permission settings)
* A property to ask the user for temporary full accuracy authorization in the location request

**Platform notes:** 
* The `ReducedAccuracy` property always returns false on non-iOS platforms
* As [described in the Apple documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600217-requesttemporaryfullaccuracyauth); on iOS the temporary full accuracy request requires a purpose description to be added to the `NSLocationTemporaryUsageDescriptionDictionary` in the app's plist file. The key `XamarinEssentialsFullAccuracyUsageDescription` was used for this purpose.

### Bugs Fixed ###

- Fixes issue #1523

### API Changes ###

Added: 
 
- `bool Location.ReducedAccuracy { get; set; }`
- `bool GeolocationRequest.RequestFullAccuracy { get; set; }`

### PR Checklist ###

- [X] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of `main` at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

2021-04-12 20:23 UTC, jamesmontemagno requested changes
I think beyond my feedback seems fine. XML docs need to be updated, but besides that is good.

2021-04-12 20:23 UTC, jamesmontemagno commented on Xamarin.Essentials/Geolocation/Geolocation.ios.macos.cs
> +            if (UIKit.UIDevice.CurrentDevice.CheckSystemVersion(14, 0))
You can use our Platform helpers or deviceinfo. We like to re-use our logic.

2021-04-13 14:12 UTC, leonluc-dev commented
@jamesmontemagno I've adjusted the version check to use the DeviceInfo API as suggested

2021-04-14 04:58 UTC, jamesmontemagno requested changes

2021-04-14 04:58 UTC, jamesmontemagno commented on Xamarin.Essentials/Geolocation/Geolocation.ios.macos.cs
> +            if (DeviceInfo.Version.Major >= 14)
```suggestion
            if (Platform.HasOSVersion(14,0))
```

2021-04-14 04:58 UTC, jamesmontemagno commented on Xamarin.Essentials/Geolocation/Geolocation.ios.macos.cs
> +            if (DeviceInfo.Version.Major >= 14)
```suggestion
            if (Platform.HasOSVersion(14,0))
```

2021-04-16 09:53 UTC, leonluc-dev commented
@jamesmontemagno The suggested changes have been applied

2021-04-21 23:17 UTC, jamesmontemagno approved these changes

2021-05-24 14:14 UTC, 111mma approved these changes

2022-04-05 09:21 UTC, jfversluis commented
Not sure if we should still pull this in for Xamarin.Essentials since it's adding APIs but at the same time it also supports newer iOS functionalities. THoughts @jamesmontemagno ?

2022-04-06 16:41 UTC, jamesmontemagno commented
I'm relatively fine with it if we do a 1.8.0

2023-08-28 13:12 UTC, mina5500 commented
@jamesmontemagno @jfversluis 
is it released in Xamarin.Essentials version 1.8.0 ?

2023-08-30 11:58 UTC, jfversluis approved these changes
Looks like this exact code is running in .NET MAUI without too many problems and we have updated Xamarin.Essentials with another major version, so let's do it.

2023-08-30 11:58 UTC, merged