added push permissions for Android & iOS
xamarin/Essentials pull request #2063
Opened 2022-11-30 15:43 UTC by thisisthekap

### Description of Change ###

Added push notification permissions for Android and iOS to the `Permissons` component.

### Bugs Fixed ###

- Related to issue #2062

### API Changes ###

List all API changes here (or just put None), example:

Added: 
 
- Permission `Permissions.PushNotification`
- Permission `Permissions.ProvisionalPushNotification`

Changed:

None
 
### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests
- [ ] Has samples
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))
  - Omitted, because msbuild tasks given in link is failing

2022-11-30 15:45 UTC, thisisthekap commented
@microsoft-github-policy-service agree [company="fun.music IT GmbH"]

2022-11-30 15:45 UTC, thisisthekap commented
@microsoft-github-policy-service agree company="fun.music IT GmbH"

2022-12-02 03:28 UTC, trampster commented
We also need this change

2022-12-05 14:31 UTC, jfversluis requested changes

2022-12-05 14:31 UTC, jfversluis commented on Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs
> +                EnsureDeclared();
There is no `RequiredInfoPlistKeys` override. I assume that we want to check if there is a plist entry/entries for push notifications?

2022-12-05 15:14 UTC, thisisthekap commented
Good idea. Will do.

2022-12-05 20:12 UTC, jamesmontemagno commented
I am not sure how many large changes we want to introduce into Xamarin.Essentials where new work should be done directly in .NET MAUI. I only recommend small bug fixes and maintenance IMHO.

This functionality could be achieved today via https://learn.microsoft.com/en-us/xamarin/essentials/permissions?context=xamarin%2Fandroid&tabs=android#extending-permissions

2022-12-07 09:27 UTC, closed without merging

2023-06-05 11:44 UTC, thisisthekap commented
@jfversluis As Xamarin.Forms is going to support Android 16 (a prerelease doing so is available at https://github.com/xamarin/Xamarin.Forms/releases/tag/beta-5.0.0-sr15-pre1), I think this PR should be reevaluated.

2023-08-19 10:51 UTC, lassana commented
This has to be reevaluated. Xamarin (and Xamarin.Forms) is claimed to be supported till April 2024, and notification permission is a core part of Android 13 which Xamarin claims to support.

2023-08-22 08:01 UTC, Jerome-Liger commented
Google force to update all our apps to target Android13 before 31/08/2023 on the PlayStore, so please, do not forget Xamarin.Forms apps IN PRODUCTION :  August 2023 -> April 2024 : it has to be implemented for me.
MAUI (and all the ecosystem) is far away to be ready to migrate all our xamarin.forms production apps...

2023-08-22 12:28 UTC, lndalmd commented
Same here!!!!We are also concerned about Xamarin.Forms ending support until all of our project dependencies have been migrated to MAUI.Leandro AlmeidaEm 22 de ago. de 2023, à(s) 05:02, Jérôme Liger ***@***.***> escreveu:﻿
Google force to update all our apps to target Android13 before 31/08/2023 on the PlayStore, so please, do not forget Xamarin.Forms apps IN PRODUCTION :  August 2023 -> April 2024 : it has to be implemented for me.
MAUI (and all the ecosystem) is far away to be ready to migrate all our xamarin.forms production apps...

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>