Patch 1
xamarin/Essentials pull request #2074
Opened 2023-01-31 16:25 UTC by ivosnoza

### Description of Change ###

Fix typos aysnc -> async in MainThread.cs

### Bugs Fixed ###

- Related to issue #

No ticket, just documentation fix

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of `main` at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation ([see walkthrough](https://github.com/xamarin/Essentials/wiki/Documenting-your-code-with-mdoc))

2023-02-02 13:35 UTC, jfversluis requested changes
Just the one thing, otherwise: thank you for doing this!

2023-02-02 13:35 UTC, jfversluis commented on docs/en/Xamarin.Essentials/FilePicker.xml
> +        <summary>Starts file picker for selecting files.</summary>
I think you changed the wrong one here. The one down below seems the one that is actually wrong on line 63

2023-02-03 12:04 UTC, ivosnoza commented
> @microsoft-github-policy-service agree

2023-02-07 10:55 UTC, jfversluis approved these changes

2023-02-07 10:55 UTC, merged

2023-02-07 10:56 UTC, jfversluis commented
Thank you so much!